"""Initial books table

Revision ID: b5962ce3a8c0
Revises: 
Create Date: 2025-06-10 13:29:09.185871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5962ce3a8c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Full_Name', sa.String(length=100), nullable=False),
    sa.Column('Car', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Client', sa.String(length=100), nullable=False),
    sa.Column('Date', sa.String(length=25), nullable=False),
    sa.Column('route', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Orders')
    op.drop_table('Drivers')
    # ### end Alembic commands ###
